"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Users = exports.User = exports.Geo = exports.Address = void 0;
var address_js_1 = require("./users/address.js");
Object.defineProperty(exports, "Address", { enumerable: true, get: function () { return address_js_1.Address; } });
var geo_js_1 = require("./users/geo.js");
Object.defineProperty(exports, "Geo", { enumerable: true, get: function () { return geo_js_1.Geo; } });
var user_js_1 = require("./users/user.js");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return user_js_1.User; } });
var users_js_1 = require("./users/users.js");
Object.defineProperty(exports, "Users", { enumerable: true, get: function () { return users_js_1.Users; } });
