// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { User } from '../users/user.js';


export class Users {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Users {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUsers(bb:flatbuffers.ByteBuffer, obj?:Users):Users {
  return (obj || new Users()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUsers(bb:flatbuffers.ByteBuffer, obj?:Users):Users {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Users()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

list(index: number, obj?:User):User|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new User()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

listLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startUsers(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addList(builder:flatbuffers.Builder, listOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, listOffset, 0);
}

static createListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endUsers(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUsers(builder:flatbuffers.Builder, listOffset:flatbuffers.Offset):flatbuffers.Offset {
  Users.startUsers(builder);
  Users.addList(builder, listOffset);
  return Users.endUsers(builder);
}
}
